//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnhancementCalculator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnhancementCalculator.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топор Баракиэля.
        /// </summary>
        internal static string BarakielAxe {
            get {
                return ResourceManager.GetString("BarakielAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трезубец Чудовища.
        /// </summary>
        internal static string BeastTrident {
            get {
                return ResourceManager.GetString("BeastTrident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цестус Беллиона.
        /// </summary>
        internal static string BellionsCestus {
            get {
                return ResourceManager.GetString("BellionsCestus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клинок Берсерка.
        /// </summary>
        internal static string BerserkerSword {
            get {
                return ResourceManager.GetString("BerserkerSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Костолом.
        /// </summary>
        internal static string Bonebreaker {
            get {
                return ResourceManager.GetString("Bonebreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лук Угрозы.
        /// </summary>
        internal static string BoP {
            get {
                return ResourceManager.GetString("BoP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ветвь Древа Жизни.
        /// </summary>
        internal static string BranchOfMotherTree {
            get {
                return ResourceManager.GetString("BranchOfMotherTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пылающий Череп Дракона.
        /// </summary>
        internal static string BurningDragonSkull {
            get {
                return ResourceManager.GetString("BurningDragonSkull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рука Кабрио.
        /// </summary>
        internal static string CabriosHand {
            get {
                return ResourceManager.GetString("CabriosHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кровавый Лук.
        /// </summary>
        internal static string CarnageBow {
            get {
                return ResourceManager.GetString("CarnageBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клеймор.
        /// </summary>
        internal static string Claymore {
            get {
                return ResourceManager.GetString("Claymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кристальный Кинжал.
        /// </summary>
        internal static string CrystalDagger {
            get {
                return ResourceManager.GetString("CrystalDagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проклятая Дага.
        /// </summary>
        internal static string CursedMaingauche {
            get {
                return ResourceManager.GetString("CursedMaingauche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кристалл Дэймона.
        /// </summary>
        internal static string DaemonCrystall {
            get {
                return ResourceManager.GetString("DaemonCrystall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дамаскус.
        /// </summary>
        internal static string Damaskus {
            get {
                return ResourceManager.GetString("Damaskus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темный Легион.
        /// </summary>
        internal static string DarkLegionsEdge {
            get {
                return ResourceManager.GetString("DarkLegionsEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топор Мертвеца.
        /// </summary>
        internal static string DeadmensGlory {
            get {
                return ResourceManager.GetString("DeadmensGlory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кинжал Демона.
        /// </summary>
        internal static string DemonDagger {
            get {
                return ResourceManager.GetString("DemonDagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клыки Демона.
        /// </summary>
        internal static string DemonFangs {
            get {
                return ResourceManager.GetString("DemonFangs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посох Демона.
        /// </summary>
        internal static string DemonStaff {
            get {
                return ResourceManager.GetString("DemonStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посох Даспариона.
        /// </summary>
        internal static string DesparionStaff {
            get {
                return ResourceManager.GetString("DesparionStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крушитель Рока.
        /// </summary>
        internal static string DoomCrusher {
            get {
                return ResourceManager.GetString("DoomCrusher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погибель Дракона.
        /// </summary>
        internal static string DragonGrinder {
            get {
                return ResourceManager.GetString("DragonGrinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Убийца Драконов.
        /// </summary>
        internal static string DragonSlayer {
            get {
                return ResourceManager.GetString("DragonSlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дамаскус*Дамаскус.
        /// </summary>
        internal static string DualDamaskus {
            get {
                return ResourceManager.GetString("DualDamaskus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Катана*Катана.
        /// </summary>
        internal static string DualKatana {
            get {
                return ResourceManager.GetString("DualKatana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длинный Меч Самурая*Длинный Меч Самурая.
        /// </summary>
        internal static string DualSLS {
            get {
                return ResourceManager.GetString("DualSLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клинок Таллума*Дамаскус.
        /// </summary>
        internal static string DualTallumDamaskus {
            get {
                return ResourceManager.GetString("DualTallumDamaskus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меч Рыцаря*Меч Эльфов.
        /// </summary>
        internal static string DualTopD {
            get {
                return ResourceManager.GetString("DualTopD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Топор Затмения.
        /// </summary>
        internal static string EclipseAxe {
            get {
                return ResourceManager.GetString("EclipseAxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меч Затмения.
        /// </summary>
        internal static string EclipseSword {
            get {
                return ResourceManager.GetString("EclipseSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меч Стихий.
        /// </summary>
        internal static string ElementalSword {
            get {
                return ResourceManager.GetString("ElementalSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элизиум.
        /// </summary>
        internal static string Elysium {
            get {
                return ResourceManager.GetString("Elysium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лук Превосходства.
        /// </summary>
        internal static string EminenceBow {
            get {
                return ResourceManager.GetString("EminenceBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Молот Гигантов.
        /// </summary>
        internal static string GiantsHammer {
            get {
                return ResourceManager.GetString("GiantsHammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глефа.
        /// </summary>
        internal static string Glaive {
            get {
                return ResourceManager.GetString("Glaive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Молот Гномов.
        /// </summary>
        internal static string GnomeHammer {
            get {
                return ResourceManager.GetString("GnomeHammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большая Пата.
        /// </summary>
        internal static string GreatPata {
            get {
                return ResourceManager.GetString("GreatPata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большой Меч.
        /// </summary>
        internal static string Greatsword {
            get {
                return ResourceManager.GetString("Greatsword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меч Стража.
        /// </summary>
        internal static string GuardianSword {
            get {
                return ResourceManager.GetString("GuardianSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алебарда.
        /// </summary>
        internal static string Halberd {
            get {
                return ResourceManager.GetString("Halberd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нож Ада.
        /// </summary>
        internal static string HellKnife {
            get {
                return ResourceManager.GetString("HellKnife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меч Гомункула.
        /// </summary>
        internal static string Homuncul {
            get {
                return ResourceManager.GetString("Homuncul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Молот Ледяной Бури.
        /// </summary>
        internal static string IceStormHammer {
            get {
                return ResourceManager.GetString("IceStormHammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меч Ипоса.
        /// </summary>
        internal static string IposSword {
            get {
                return ResourceManager.GetString("IposSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кости Каим Ванула.
        /// </summary>
        internal static string KaimVanul {
            get {
                return ResourceManager.GetString("KaimVanul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Катана.
        /// </summary>
        internal static string Katana {
            get {
                return ResourceManager.GetString("Katana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легкий Лук.
        /// </summary>
        internal static string LightCrossbow {
            get {
                return ResourceManager.GetString("LightCrossbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мастер Инферно.
        /// </summary>
        internal static string MasterInferno {
            get {
                return ResourceManager.GetString("MasterInferno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мистический Меч.
        /// </summary>
        internal static string MysticalSword {
            get {
                return ResourceManager.GetString("MysticalSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секира Орков.
        /// </summary>
        internal static string OrcPolearm {
            get {
                return ResourceManager.GetString("OrcPolearm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меч Паагрио.
        /// </summary>
        internal static string PaagrioSword {
            get {
                return ResourceManager.GetString("PaagrioSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пика.
        /// </summary>
        internal static string Pike {
            get {
                return ResourceManager.GetString("Pike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лук Шиид.
        /// </summary>
        internal static string ShyidBow {
            get {
                return ResourceManager.GetString("ShyidBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клинок Сирры.
        /// </summary>
        internal static string SirrasBlade {
            get {
                return ResourceManager.GetString("SirrasBlade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длинный Меч Самурая.
        /// </summary>
        internal static string SLS {
            get {
                return ResourceManager.GetString("SLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ураган Собекка.
        /// </summary>
        internal static string SobbeksTempest {
            get {
                return ResourceManager.GetString("SobbeksTempest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пронзатель Душ.
        /// </summary>
        internal static string SoulBow {
            get {
                return ResourceManager.GetString("SoulBow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Душегуб.
        /// </summary>
        internal static string SoulSeparator {
            get {
                return ResourceManager.GetString("SoulSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассеиватель Заклинаний.
        /// </summary>
        internal static string SpellBreaker {
            get {
                return ResourceManager.GetString("SpellBreaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шипованный Джамадхар.
        /// </summary>
        internal static string SpikedJamadhar {
            get {
                return ResourceManager.GetString("SpikedJamadhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посох Злых Духов.
        /// </summary>
        internal static string StaffOfEvilSpirit {
            get {
                return ResourceManager.GetString("StaffOfEvilSpirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посох Жизни.
        /// </summary>
        internal static string StaffOfLife {
            get {
                return ResourceManager.GetString("StaffOfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звезда Боли.
        /// </summary>
        internal static string StarOfPain {
            get {
                return ResourceManager.GetString("StarOfPain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Буря Наги.
        /// </summary>
        internal static string StormNaga {
            get {
                return ResourceManager.GetString("StormNaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меч Гигантов.
        /// </summary>
        internal static string SwordOfGiants {
            get {
                return ResourceManager.GetString("SwordOfGiants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Легендарный Меч.
        /// </summary>
        internal static string SwordOfMiracles {
            get {
                return ResourceManager.GetString("SwordOfMiracles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Меч Вальхаллы.
        /// </summary>
        internal static string SwordOfValhalla {
            get {
                return ResourceManager.GetString("SwordOfValhalla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глефа Таллума.
        /// </summary>
        internal static string TallumGlave {
            get {
                return ResourceManager.GetString("TallumGlave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарбар.
        /// </summary>
        internal static string Tarbar {
            get {
                return ResourceManager.GetString("Tarbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык Темис.
        /// </summary>
        internal static string TemisTongue {
            get {
                return ResourceManager.GetString("TemisTongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копье Тифона.
        /// </summary>
        internal static string TyphonPike {
            get {
                return ResourceManager.GetString("TyphonPike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слезы Чародея.
        /// </summary>
        internal static string WizardsTears {
            get {
                return ResourceManager.GetString("WizardsTears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Булава Якса.
        /// </summary>
        internal static string Yaksa {
            get {
                return ResourceManager.GetString("Yaksa", resourceCulture);
            }
        }
    }
}
